name: riverpod_arch_app
description: "Various application architectures based on the riverpod package"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0-dev.3
  cardoteka: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
